DB_HOST = 'localhost'
DB_PORT = 3306
DB_NAME = 'controversy'
DB_PASSWORD = 'pwd' # change
DB_USER = 'root' # maybe change
SECRET_KEY = '23jlvafi23josdnnaDFASs' # should change
API_KEY = 'twitter api' # change
API_SECRET = 'twitter api secret' # change
NYT_KEY = 'nyt article search key' # change
NYT_COMMUNITY_KEY = 'nyt community api key' # change
REDIS_HOST = 'localhost'
REDIS_PORT = '6378'
TWILIO_SID = 'twilio key' # change
TWILIO_AUTH_TOKEN = 'twilio auth key' # change
ADMIN_PHONE = '+1911' # change
CAPTCHA_PUBLIC = 'reCAPTCHA key' # change
CAPTCHA_PRIVATE = 'reCAPTCHA secret key' # change
DEBUG = True
